name: Crowdin

on:
  workflow_dispatch: ~
  schedule:
    - cron:  '0 8 * * *'

jobs:
  synchronize-with-crowdin:
    name: Download translations from Crowdin

    if: github.repository == 'revive-adserver/revive-adserver'

    env:
      PHP_EXTENSIONS: none, ctype, curl, dom, fileinfo, intl, json, libxml, mbstring, mysqli, openssl, pgsql, simplexml, tokenizer, xml, xmlwriter, zip

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: ${{ env.PHP_EXTENSIONS }}
          coverage: none
          tools: composer

      - name: Install dependencies with Composer
        run: composer install --no-interaction --no-ansi --no-progress

      - name: Download from Crowdin
        if: env.CROWDIN_PROJECT_ID && env.CROWDIN_PERSONAL_TOKEN
        uses: revive-adserver/crowdin-github-action@master
        with:
          config: crowdin.yml.dist
          upload_sources: false
          upload_translations: false
          download_translations: true
          localization_branch_name: crowdin_translations
          create_pull_request: true
          pull_request_title: 'New Crowdin Translations'
          pull_request_body: 'Updated translations from Crowdin'
          pull_request_base_branch_name: 'master'
          pull_request_labels: Translation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
