name: "Crowdin: Upload translation sources"

on:
  push:
    branches: [master]

jobs:
  upload-to-crowdin:
    runs-on: ubuntu-latest
    if: github.repository == 'revive-adserver/revive-adserver'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Crowdin Action
        if: env.CROWDIN_PROJECT_ID && env.CROWDIN_PERSONAL_TOKEN
        uses: revive-adserver/crowdin-github-action@master
        with:
          config: crowdin.yml.dist
          upload_sources: true
          upload_translations: false
          download_translations: false
          create_pull_request: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
