name: Test Report

on:
  workflow_call:
    inputs:
      sha:
        required: false
        type: string

permissions:
  checks: write

jobs:
  tests-report:
    name: Generate test report

    runs-on: ubuntu-latest

    steps:
      - name: Download Test Report
        uses: dawidd6/action-download-artifact@v3
        with:
          name: test-results
#          workflow: ${{ github.event.workflow.id }}
#          run_id: ${{ github.event.workflow_run.id }}
          if_no_artifact_found: warn

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        with:
          commit: ${{ inputs.sha }}
          report_paths: '**/build/test-reports/*.xml'
